### ISSUE TITLE
QtWebkit leaks threads when using <video> tag

### ISSUE THREAD

**Issue by patxitron** [Metrological/buildroot#101]
I've build a buildroot cloned today from the repository with the rpi2_qt5webkit_defconfig. When using qtbrowser to view a HTML page that plays some videos in a playlist and then loop that playlist I can see (using htop) that for each time the video changed, the number of qtbrowser threads increases by one and never decreases.

Best regards.

**Comment by albertd** [comment]
We're moving to WPE (WebKit Wayland)
