### ISSUE TITLE
Blank page with remote inspector

### ISSUE THREAD

**Issue by madanagopalt** [Metrological/buildroot#107]
Hi,

I am trying wpe wayland and opened remote inspector, only by the below command:

export WEBKIT_INSPECTOR_SERVER=<ipaddress:port>

I opened http://ipaddress:port in firefox. It is showing the opened URL in inspectable views. When i click that link,  JS Pages are downloaded but showing empty page. Please suggest a way to debug this.

Regards,
Madan

**Comment by albertd** [comment]
Please use webkit nightly to view the webinspector

**Comment by woutermeek** [comment]
Hi Madan,

You need to use the latest webkit nightly to view the inspector.
http://nightly.webkit.org/

Kind regards,

Wouter

**Comment by madanagopalt** [comment]
Oh, ok, could you please tell, do i need any more settings to enable the webinspector?.

**Comment by madanagopalt** [comment]
I am not seeing any script for run-wpe. I want to run it on weston compositor.Please suggest the way to do.

**Comment by philn** [comment]
Setting WEBKIT_INSPECTOR_SERVER and using run-wpe in combination with the webkit nightly should be enough.

**Comment by madanagopalt** [comment]
Hi,

I am working on linux. I am unable to see run-wpe on downloading the source code mentioned in site http://nightly.webkit.org/. 

Also, i tried executing the below commands:

1,
$ Tools/Scripts/update-webkitwpe-libs

The above script is not present.

2,
madan@madan:~/WebKit-r189384$ Tools/Scripts/build-webkit --wpe --threaded-compositor

====================================================================
 WebKit is now built (00m:00s). 
====================================================================

But i didn't get run-wpe binary. Please suggest a way to build. It has been mentioned, nightly buils is available only for Mac OS. If i want to build wpe-webkit for linux, please suggest the way to do. Thanks.

Regards,
Madan

**Comment by philn** [comment]
You're not using the right git repository.

To use WPE on Linux you need to clone this repo: https://github.com/WebKitForWayland/webkit

**Comment by philn** [comment]
To use the WebInspector on Linux your only option currently is a very recent version of webkitgtk (2.10 at least). The MiniBrowser should be able to act as a client to the WebInspector server.

**Comment by madanagopalt** [comment]
Yes, i already tried with that repo. I got blank page, while running inspector on firefox. Is it like, today i have to download and build once?. Please clarify.

Regards,
Madan

**Comment by philn** [comment]
Firefox isn't compatible with WebKit's web inspector.

**Comment by madanagopalt** [comment]
Ok, could you please tell what browser i can use on linux to check the web inspector.

**Comment by madanagopalt** [comment]
I tried with another wpe browser also and behaviour is same, could you please suggest what browser i can try ?

**Comment by madanagopalt** [comment]
Please let me know,which browser I can use in Linux for accessing webinspector in wpewebkit.

**Comment by philn** [comment]
Did you read https://github.com/Metrological/buildroot/issues/107#issuecomment-144053250 ?

**Comment by madanagopalt** [comment]
Ok,so I have to check only with gtk and not with wpe?.Any release is planned for inspector working with wpe,because I am using wpe webjit and not gtk. Or any configurations I might have missed?.please suggest.

**Comment by philn** [comment]
This is the only solution currently. Build webkitgtk trunk and use MiniBrowser: http://trac.webkit.org/wiki/BuildingGtk

**Comment by madanagopalt** [comment]
Ok,thanks
