### ISSUE TITLE
WPE: cookie storage across restarts?

### ISSUE THREAD

**Issue by depili** [Metrological/buildroot#90]
Is it possible to get WPE to remember cookies between restarts? So far it seems to only keep localstorage items in ~/.local/share/wpe/localstorage/ but cookies aren't saved. With qtbrowser there was the --cookie-store parameter, but nothing like that seems to exist for WPE.

Would it be possible to get wpe to save its cookies somehow?

Asking because currently our infoscreen / digital signage project relies on cookies to store information in the webgl display clients ( https://github.com/depili/isk and https://github.com/iskcrew/iskdpy )

**Comment by albertd** [comment]
Has been resolved in the latest WPE
