### ISSUE TITLE
Strange issue with audio through RPI 3.5mm

### ISSUE THREAD

**Issue by flyandi** [Metrological/buildroot#93]
Howdy,
Did anyone experience the same strange issue. I added the asta-tools to my buildroot and use amixer to set the output of audio to the 3.5mm (via amixer cset numid=3 1) and the speaker-test works as expected. However when starting either wpe or qt5browser and using web audio the sound always defaults to HDMI even when forced through the 3.5mm.

Anyone know how to solve this?

**Comment by abiehaf** [comment]
I solved this by editing /etc/xdg/gstomx.conf
Try to change the value of rank in omxanalogaudiosink and omxhdmaudiosink


Regards,

Abi Hafshin Alfarouq
http://hafs.in/

**Comment by flyandi** [comment]
Thx  - that worked!

**Comment by abiehaf** [comment]
You are welcome


Regards,

Abi Hafshin Alfarouq
http://hafs.in/

**Comment by michaelhanin** [comment]
Hello,
which value need to be change for rank in /etc/xdg/gstomx.conf to set sound go to jack ?

thank you
